name: Prerelease

on:
  push:
    branches:
      - development

jobs:
  tests:
    name: Tests
    if: "!contains(github.event.head_commit.message, '__SEMANTIC RELEASE VERSION UPDATE__')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        cfengine: ["lucee@5", "adobe@2018", "adobe@2021" ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Set Up CommandBox
        uses: Ortus-Solutions/setup-commandbox@v2.0.1

      - name: Install dependencies
        run: |
          box install

      - name: Start server
        run: |
          box server start cfengine=${{ matrix.cfengine }} --noSaveSettings
          # Install Adobe 2021 cfpm modules
          if [[ "${{ matrix.cfengine }}" == "adobe@2021" ]] ; then
            box run-script install:2021
          fi

      - name: Run TestBox Tests
        run: box testbox run
